--- # ---------------------------------------------------------------------------
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definition of organizations managing orderer nodes
OrdererOrgs:
  # ---------------------------------------------------------------------------
  # Orderer
  # ---------------------------------------------------------------------------
  - Name: Orderer
    Domain: dsct.com
    # ---------------------------------------------------------------------------
    # "Specs" - See PeerOrgs below for complete description
    # ---------------------------------------------------------------------------
    Specs:
      - Hostname: orderer
# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
  # ---------------------------------------------------------------------------
  # Manufacturer
  # ---------------------------------------------------------------------------
  - Name: Manufacturer
    Domain: manufacturer.dsct.com
    Template:
      Count: 1
    Users:
      Count: 1
  # ---------------------------------------------------------------------------
  # Delear
  # ---------------------------------------------------------------------------
  - Name: Delear
    Domain: delear.dsct.com
    Template:
      Count: 1
    Users:
      Count: 1

  # ---------------------------------------------------------------------------
  # Hosp
  # ---------------------------------------------------------------------------
  - Name: Hosp
    Domain: hosp.dsct.com
    Template:
      Count: 1
    Users:
      Count: 1
